name: 'Pawel Miszkurka  '
description: 'Automagically create a JIRA issue in active sprint'
author: 'cko-prism'
inputs:
  JIRA_HOST:
    required: true
    description: 'JIRA host (eg. https://checkout.atlassian.net)'
  JIRA_API_TOKEN:
    required: true
    description: 'JIRA API token (create one at https://id.atlassian.com/manage-profile/security/api-tokens)'
  JIRA_BOARD_ID:
    required: true
    description: 'ID of the board you want to add the JIRA ticket to (eg. 168)'
  JIRA_PROJECT_KEY:
    required: true
    description: 'Key of the project you want to add the JIRA ticket to (eg. PRISM)'
  JIRA_TRANSITION_ID:
    required: true
    description: 'Transition ID to put the JIRA ticket in the right column (eg. 81)'
    default: '81'
  JIRA_ACTIVE_SPRINT_FIELD:
    required: true
    description: 'The custom field that displays the current, active sprint of the project (eg. customfield_10122)'
    default: 'customfield_10122'
  JIRA_TICKET_SUMMARY:
    required: true
    description: 'The custom field that sets jira ticket title'
  JIRA_TICKET_DESCRIPTION:
    description: 'The custom field that sets jira description'
    default: ''

outputs:
  JIRA_TICKET_ID: 
    description: 'Jira ticket ID'
  JIRA_TICKET_URI: 
    description: 'Jira ticket URI' 

runs:
  using: 'node12'
  main: 'dist/index.js'
